### ISSUE TITLE
Unable to mock domain class

### ISSUE THREAD

**Issue by ralphga** [apex-enterprise-patterns/at4dx#25]
Hi John,

I'm very new to Apex Common and is very interested on trying it. I'm currently blocked when doing a unit test for a service that is calling a domain class. For my sample, I'm trying to convert the batch retry framework by afawcett.

The error I'm getting is: System.TypeException: Invalid conversion from runtime type IInvoices to fflib_SObjectDomain.IConstructable

Here are my code and also the unit test is below. Thank you in advance and really appreciate the help.

```
public interface IInvoices
    extends IApplicationSObjectDomain
{
    void executeInvoiceGenerationJob(List<Order> orders, fflib_ISObjectUnitOfWork uow);
}

```

```
public with sharing class Invoices
    extends ApplicationSObjectDomain
    implements IInvoices
{
    public static IInvoices newInstance(List<Invoice__c> records)
    {
        return (IInvoices) Application.Domain.newInstance(records);
    }

    public Invoices(List<Invoice__c> records)
    {
        super(records);

          // don't enforce CRUD security for Invoice records
        this.Configuration.disableTriggerCRUDSecurity();
    }

    public class Constructor
        implements fflib_SObjectDomain.IConstructable
    {
        public fflib_SObjectDomain construct(List<SObject> sObjectList)
        {
            return new Invoices(sObjectList);
        }
    }

    public void executeInvoiceGenerationJob(List<Order> orders, fflib_ISObjectUnitOfWork uow) 
    {
        List<Invoice__c> invoices = new List<Invoice__c>();
        for(Order order : orders) {
            produceSomeExceptions(order.Name);
            Invoice__c invoice = new Invoice__c();
            invoice.DueDate__c = System.today().addDays(30);
            invoice.Paid__c = false;
            invoice.Order__c = order.Id;
            invoice.Amount__c = order.TotalAmount;
            invoices.add(invoice);
            order.Invoiced__c = true;
            //register order for update 
            uow.registerDirty(order);    

            //register invoices for new
            uow.registerNew(invoice);        
        }
    }

    // Produce some exceptions, some catchable, some not...
    private void produceSomeExceptions(String orderName) {
        switch on orderName {
           when 'Ref:100' {
               // Standard exception
               throw new InvoiceGenerationException('Order Ref:100 is invalid.');
           }
           when 'Ref:300' {
               // Divide by zero!
               Integer newAmount = 20 / 0;
           }
        //    when 'Ref:500' {
        //         // Limits exception
        //         for(Integer idx=0; idx<201; idx++) {
        //             Order order = [select Id from Order limit 1];
        //         }
        //    }
        }
    }

    public class InvoiceGenerationException extends Exception {} 
}
```

```
public class InvoicesServiceImpl implements IInvoicesService {
    public void executeInvoiceGenerationJob(List<SObject> scope)
    {           
        // Create unit of work to capture work and commit it under one transaction
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

        // Query Orders that are not yet invoiced          
        List<Order> orders = OrdersSelector.newInstance().selectByScopeAndIsInvoiced(scope, false);                    
        IInvoices invs = Invoices.newInstance(new List<Invoice__c>());
        invs.executeInvoiceGenerationJob(orders, uow);
        
        uow.commitWork();
    }

    public List<Order> getNotInvoicedOrdersThisWeek()
    {
        // Query Orders that are not yet invoiced
        return OrdersSelector.newInstance().selectByEffectiveDateAndIsInvoiced(false);
    }

    public void handleGenerationJobErrors(brf_BatchableError error)
    {
        // Update the effected orders with the error for further review

        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();
        IOrders orders = Orders.newInstance(new List<Order>());
        orders.updateOrdersByErrorId(error, uow);     
    }
}
```

```
@IsTest
private class InvoicesServiceImplTest {
    @IsTest
    private static void callingServiceExecuteInvoiceGenerationJob_ShouldCallOrdersSelectorAndDomain()
    {
        // Create mocks
        fflib_ApexMocks mocks = new fflib_ApexMocks();
        IApplicationSObjectUnitOfWork uowMock = (IApplicationSObjectUnitOfWork) mocks.mock( IApplicationSObjectUnitOfWork.class );               
        IInvoices domainMock = (IInvoices) mocks.mock( IInvoices.class );       
        IOrdersSelector selectorMock =  (IOrdersSelector) mocks.mock( IOrdersSelector.class );

        // Given
        mocks.startStubbing();
        Order ord = new Order(
            Id = fflib_IDGenerator.generate(Order.SObjectType),
            Name = 'Ref:0',
            Invoiced__c = false,
            Status = 'Draft');

        List<string> orderIds = new List<string>();
        orderIds.add(ord.Id);        
        List<Order> testOrders = new List<Order>();
        testOrders.add(ord);

        SObject obj = new Order();
        obj.Id = ord.Id;
        List<SObject> scope = new List<SObject> { obj };
        mocks.when(domainMock.sObjectType()).thenReturn(Invoice__c.SObjectType);             
        mocks.when(selectorMock.sObjectType()).thenReturn(Order.SObjectType);
        mocks.when(selectorMock.selectByScopeAndIsInvoiced(scope, false)).thenReturn(testOrders);

        mocks.stopStubbing();
        //set mocks
        Application.UnitOfWork.setMock(uowMock);
        Application.Selector.setMock(selectorMock);
        Application.Domain.setMock(domainMock);

        //When
        InvoicesService.executeInvoiceGenerationJob(scope);

        // Then
        ((IOrdersSelector) 
            mocks.verify(selectorMock)).selectByScopeAndIsInvoiced(scope, false);
        ((IInvoices) 
            mocks.verify(domainMock)).executeInvoiceGenerationJob(testOrders, uowMock);
        ((fflib_ISObjectUnitOfWork) 
            mocks.verify(uowMock, 1)).commitWork();
    }
}
```

**Comment by ImJohnMDaniel** [comment]
@Ralphga. Does your binding record for Invoice map to the Apex class `Invoices` or `Invoices.Constructor`??

**Comment by ralphga** [comment]
Hi @ImJohnMDaniel , thank you for your response.
It currently maps to Invoices.Constructor. Should it be just Invoices?

**Comment by ImJohnMDaniel** [comment]
Nope.  `Invoices.Constructor` is correct. Can you post the binding records that you have?  Also, are the code fragments you supplied sufficient to reproduce the issue??

**Comment by ralphga** [comment]
[DomainConstructorError.zip](https://github.com/ImJohnMDaniel/at4dx/files/3253325/DomainConstructorError.zip)


I'm attaching the bindings and the Order selector in a zip. Appreciate the help!

**Comment by ImJohnMDaniel** [comment]
Thanks.  

Unfortunately, I am on vacation for the next 12 days and I don’t have access to my computer.

I will take a look when I get back.

Cheers

**Comment by ralphga** [comment]
No worries! I will wait 'til then. Thank you and enjoy your vacation!

**Comment by dmchaplin** [comment]
I think I'm having the exact same issue.   Any progress on this?

**Comment by dmchaplin** [comment]
I've got further testing to do, but I think I've isolated it to IApplicationSObjectDomain newInstance(List<SObject> records) in Application.cls

If I'm understanding it correctly, the Mock framework has already constructed the domain class, but this method does not know that.

I'm having luck with this:
'        public IApplicationSObjectDomain newInstance(List<SObject> records)
        {
            SObjectType domainSObjectType = records.getSObjectType();
            if (domainSObjectType == null)
                throw new DeveloperException('Unable to determine SObjectType');

            // Construct Domain class passing in the queried records
            object returnObject =  di_Injector.Org.getInstance( IApplicationSObjectDomain.class, domainSObjectType );

            //if returned class is constructable, then construct
            //otherwise assume that it is mocked
            IApplicationSObjectDomain returnDomain;
            If (returnObject instanceof fflib_SObjectDomain.IConstructable) {
                    fflib_SObjectDomain.IConstructable domainConstructor = (fflib_SObjectDomain.IConstructable) returnObject;
                    returnDomain = (IApplicationSObjectDomain) domainConstructor.construct(records);
            } else {
                returnDomain = (IApplicationSObjectDomain) returnObject;
            }
            return returnDomain;
        }    
'

I'm not sure if this is correct or the best method yet, so I'll hold off on a push request for now.

**Comment by stohn777** [comment]
I see and understand the cause of this issue.  Actual domain classes will implement either `fflib_SObjectDomain.IConstructable` or `fflib_SObjectDomain.IConstructable2`, whereas unit-test authors may not know of the requirement for mock domain classes.

I have a couple of high-level thoughts about how to address this.  Ideally I'd prefer detecting an incompatible mock at the time of executing `setMock`, as opposed to accepting Objects.

Thoughts; comments?

**Comment by torynet** [comment]
I don't know how we never ran into this before. I can only assume some domain classes were not mocked that should have been. We sure have now though.

Perhaps I'm not understanding what you're suggesting @stohn777 . Are you saying you would expect the dev to mock the constructor as well as the domain like this?

> `fflib_ApexMocks mocks = new fflib_ApexMocks();`
> `IDomain theDomainMock = (IDomain)mocks.mock(IDomain.class);`
> `fflib_SObjectDomain.IConstructable domainConstructorMock = (fflib_SObjectDomain.IConstructable)mocks.mock(fflib_SObjectDomain.IConstructable.class);`
> `mocks.startStubbing();`
> `mocks.when(theDomainMock.sObjectType()).thenReturn(Account.SObjectType);`
> `mocks.when(domainConstructorMock.construct(testSObjectList)).thenReturn(theDomainMock);`
> `mocks.stopStubbing();`
> `Application.Domain.setMock(theDomainMock);`

That would make sense to me, except that IConstructable is an inner class itself, which produces this:
`System.TypeException: Test.createStub() cannot be called with inner Apex classes`

So, maybe I just don't know how to mock inner classes, but if it's not possible, then I don't think that works does it?
Perhaps that's not what you meant at all.

I'm glad to see @dmchaplin has a workaround already. That seems fairly reasonable. We're already making assumptions that it will be an IConstructable. I don't really see any reason not to also assume that if it's not, then it is the thing the IConstructable would have constructed.

Perhaps I'm just missing something. Any additional feedback before I follow suit would be awesome.

Really appreciate all your hard work on this project. Thank you.

**Comment by stohn777** [comment]
@torynet  FYI.  I've been looking at this in my free time, and personally, have basically arrived at the same point as you using Apex Mocks.  The question is, "How could we mock the inner class?"  @ImJohnMDaniel mentioned that others in different conversations have brought up the concept of mocking inner classes too.

@dmchaplin's workaround looks promising to me, although I'd like to give it a bit more thought.

J.D. and I have started a conversation on the matter too, so hopefully we can track-down a recommendation soon.

**Comment by stohn777** [comment]
@torynet @dmchaplin 
Over the holidays, I'm trying to up the test coverage of the framework, and ran head-on into this issue and fully get it.  I'm adding a version of the recommend change.  Please have a look.

https://github.com/apex-enterprise-patterns/at4dx/pull/41

cc. @ImJohnMDaniel

**Comment by ImJohnMDaniel** [comment]
G'day @ralphga, @dmchaplin, and @torynet -- @stohn777 and I wanted to let you know that we believe this issue is now corrected.  Please take the latest updates from the master branch and try again.    Again, my apologies for this taken way too long to resolve.  Cheers!

**Comment by dmchaplin** [comment]
I’m glad to see that fixed.  The bummer part is that I changed jobs and my new employer does not use at4dx nor fflib.   I’m hoping to introduce the idea sometime this year.  I really miss all the advantages of using them.
