### ISSUE TITLE
When should ApplicationFactory_UnitOfWorkBinding and DomainMethodToken be used?

### ISSUE THREAD

**Issue by chazwatkins** [apex-enterprise-patterns/at4dx#60]
Hi @ImJohnMDaniel @stohn777 ,

Can you provide some examples for using `ApplicationFactory_UnitOfWorkBinding` and Domain Process Action `DomainMethodToken`?

I don't understand when I'd reach for either option.  I checked for these in at4dx-samplecode, but didn't see any examples.

Also, I found @ImJohnMDaniel response to an earlier question in #39 about `DomainMethodToken`, but would like to see an example for understanding.

_re: DomainMethodToken vs TriggerOperation -- So the thought here is that it is an "either/or" feature. You will specify the TriggerOperation approach or the DomainMethodToken approach. The DomainMethodToken option is for use cases where you are wanting to call an orchestrated domain process from a Service tier class or maybe another Domain class. In theory could call another Domain that is part of another package and simply wrap the call in a try/catch thus allowing for the functionality to be called, if the code were present in the org, and it still be loosely coupled._

Thanks for your work on this great framework!  My team and I have recently picked up AT4DX to aid us in breaking up our organization into packages.  It has been a joy to use so far.

Best Regards,
Chaz Watkins

**Comment by chazwatkins** [comment]
Thanks, @ImJohnMDaniel.

I missed the UOW examples.  Thanks for taking the time to provide the links.  I notice there is no ‘To__c’ field.  So, do I use the Binding Sequence to order the SObjextTypes as I would using ‘Application.UnitOfWork.newInstance(List<SObjectType> sobjTypeList)’?

**Comment by ImJohnMDaniel** [comment]
https://github.com/apex-enterprise-patterns/at4dx/issues/60



> Also, regarding Domain Process Bindings execution order. Given I have 2 Trigger Context Criteria and Action bindings for an object, when Criteria 1 filters down the records for Action 1 and Action 1 executes, then Criteria 2 is given only the records from Criteria 1? Is this accurate? Or is Criteria 2 given all records from Trigger.new and Trigger.old?

So, the execution order is going be a decimal; not an integer.  The "integer-side" of that number represents the "domain process id".  The "decimal-side" of that number represents the sequence for criteria/action class execution within that domain process.

Say you have three independent domain processes (i.e. DP-A, DP-B, and DP-C).  Those domain processes have the following criteria and action class constituents:

- DP-A
  - Criteria
    - C-1
    - C-2
  - Actions
    - A-1
    - A-2
- DP-B
  - Criteria
    - C-1
    - C-3
  - Actions
    - A-3
- DP-C
  - Criteria
    - C-2
    - C-4
    - C-5
  - Actions
    - A-4
    - A-5

Notice that you can reuse criteria and action classes across multiple domain processes.

In this scenario, you have three domain processes where each of those domain process should have a unique "domain process sequence Id".  We will say the following domain process sequence Ids are:
* DP-A -- 10
* DP-A -- 20
* DP-A -- 30

So, with that in mind, the domain process sequences would be the following:
- DP-A
  - Criteria
    - C-1 -- 10.10
    - C-2 -- 10.20
  - Actions
    - A-1 -- 10.10
    - A-2 -- 10.20
- DP-B
  - Criteria
    - C-1 -- 20.10
    - C-3 -- 20.20
  - Actions
    - A-3 -- 20.10
- DP-C
  - Criteria
    - C-2 -- 30.10
    - C-4 -- 30.20
    - C-5 -- 30.30
  - Actions
    - A-4 -- 30.10
    - A-5 -- 30.20

Ok.  Let's start looking at this now.

Each domain process will be treated in isolation.  If the criteria classes from domain process 10 criteria filter the active record set down to a subset for the domain process 10 actions, it will only be for those actions.  When domain process 20 begins, it will start fresh with the original set of records and the domain process 20 criteria will filter that original record set down to a subset that the domain process 20 actions will work on.  The same is true for when domain process 30 begins.  Each domain process begins with the same original group of records.  This is true regardless of whether or not the same physical crtiera or action class is utililzed in multiple domain processes.  

Also note that these domain process ids are specific to the other defining traits of the domain process.  What I mean is a domain process is classified by multiple elements: 
- the SObject involved, 
- Trigger or Domain Method context, 
- If Domain Method context, then what is the unique "domain method token", 
- If Trigger context, then what type of Trigger context -- Before Insert, After Update, etc.  

So, you could see a domain process id of "10" for all of the following combination examples:
- Account - Trigger context - BeforeInsert
- Account - Trigger context - AfterUpdate
- Contact - Trigger context - BeforeInsert
- Account - Domain Method context - unique "domain method token"
- Contact - Domain Method context - unique "domain method token"
- etc...

I hope this helps.   Let me know if you have questions.

**Comment by chazwatkins** [comment]
Thanks, @ImJohnMDaniel for the in-depth explanation of Domain Processes.  It answered my question about DP execution order perfectly.  Your explanation would be a great addition to the at4dx documentation for Domain Processes.  If you'd like, I can take what you wrote and submit a PR to the documentation.

When you reference "Domain Method context", how are those utilized?  Is this calling the Domain Process from the Domain Apex class?
