### ISSUE TITLE
Question: How do you use IDomainProcessWithParamsAction and IDomainProcessWithParamsCriteria?

### ISSUE THREAD

**Issue by chazwatkins** [apex-enterprise-patterns/at4dx#66]
Howdy folks,

I want to pass some parameters through a DomainProcess chain, but don't see any examples of how to do so.  Would you mind providing an example of how to use these interfaces?

- IDomainProcessWithParamsCriteria
- IDomainProcessWithParamsAction

Thanks for the help.

Best Regards,
Chaz Watkins

**Comment by ImJohnMDaniel** [comment]
G'day @chazwatkins.  My apologies for not getting back to you before now.  I just wanted to reach out to let you know that, first off, I haven't forgotten about this question, and, second, I have done some work to provide an example, but that work led to a bit of confusion on my part that I am trying to work through.  It is quite possible that I have not finished this feature's implementation.  I should be getting some more time to focus on this soon and should be able to get you an answer as well.  Thanks for the patience.  Cheers!

**Comment by chazwatkins** [comment]
Thanks, @ImJohnMDaniel.  If you can provide the acceptance criteria for the feature, I'm happy to help with the implementation.  This will be a nifty feature.

Best Regards,
Chaz Watkins

**Comment by chazwatkins** [comment]
Howdy, @ImJohnMDaniel - Our team is starting to utilize Domain Processes more often and needs to pass queried data through the pipelines.  Our need doesn't drive urgency for an open-source framework to implement features.  However, would you mind providing me with how you envisioned this feature to work? We can implement it as a contribution.

**Comment by ImJohnMDaniel** [comment]
G'day @chazwatkins -- Unfortunately we have not had a chance yet to look into this beyond the early attempt in June.  At this point, it is clear that this part of the feature was never completed.  So I will be looking into that in the next month or two, as time permits.   If you are interested in contributing and open a PR for discussion/review, that would awesome.  I would also be happy to help discuss preliminary technical design if that would help.

I am not sure if you are going to be able to attend Dreamforce22 or not.  If you are, feel free to reach out and we can find some time to connect.  @stohn777 and I will be presenting on AT4DX on Wednesday at 12:30 in Moscone West.  

All the best.  Cheers!

**Comment by chazwatkins** [comment]
Thanks, John.  It'd be great to talk through the technical design before giving it a go.  I suspect that will make the implementation and acceptance go quicker.

I won't be at Dreamforce in person but will attend remotely.  Glad to know you and @stohn777 will be presenting AT4DX.  I'll make sure to catch the talk.  Safe travels and good luck on the presentation.

After Dreamforce, let me know when is a good time to have a chat on this feature.

Best Regards,
Chaz Watkins

**Comment by chazwatkins** [comment]
@ImJohnMDaniel - I know you guys are busy implementing `WITH USER_MODE` in `fflib-apex-common`.  When would be a good time for us to chat about the design for this feature?  There's no rush.  I want to help out with this one.
