### ISSUE TITLE
AT4DX Documentation

### ISSUE THREAD

**Issue by chazwatkins** [apex-enterprise-patterns/at4dx#72]
Hi @ImJohnMDaniel - As requested in PR #70, I moved the docs to the wiki in my fork.  I will start contributing the docs there, and we can merge them into the main at4dx repo when ready.

Fork Wiki: https://github.com/chazwatkins/at4dx/wiki

Changes:
I started writing a draft documentation on the Domain Process feature. Check it out in [Domain Process Injection](https://github.com/chazwatkins/at4dx/wiki/Domain-Process-Injection) and let me know your feedback @ImJohnMDaniel @stohn777

So far, it's mostly a brain dump and includes some explanation provided in issues. So, I'm sure it'll need some reordering and wordsmithing.

**Comment by ImJohnMDaniel** [comment]
@chazwatkins , thats good to hear.  After a quick look, I see you are including references to the other AEP projects inside the AT4DX wiki.  Please setup similar wiki forks from those projects directly and add your thoughts there.  In the AT4DX, it is fine to link to the Mocks, Common, and Force-DI wikis.  Make sense?

**Comment by chazwatkins** [comment]
I was confused why those were already there too.  I'll remove them and they can be put on the other repos.

**Comment by chazwatkins** [comment]
I removed the other AEP repo pages as requested.

**Comment by Vacster** [comment]
Heya @chazwatkins, I was looking for AT4DX documentation and stumbled upon this.

Is there any reason you've only kept the documentation you wrote in your fork and not added it to the original repo's wiki?
It looks good to me and definitely more than enough as is to be more valuable than the current placeholder.

**Comment by chazwatkins** [comment]
@Vacster I got busy with other things and opted not to submit a PR until I found time to finish everything.  Obviously, that hasn't happened in the last year or so.  ha.  If you find the document on Domain Processes that I wrote useful, I can open a PR for it.

**Comment by Vacster** [comment]
@chazwatkins thanks for the reply. I actually learned recently that we [can't make PR's for Wiki pages in GitHub](https://github.com/orgs/community/discussions/50163).

With that in mind, I think it would be up to @ImJohnMDaniel to copy over the Wiki changes from your fork into here, which I would absolutely love if it could be done.
