### ISSUE TITLE
Unable to call TestDataSupplementer.supplement(xxx) if no implementation of TestDataSupplementer for SObjectType xxx

### ISSUE THREAD

**Issue by simon-nowak** [apex-enterprise-patterns/at4dx#79]
Hello here,

First I'm not sure if it's a bug or a wanted behaviour. 

**Is your feature request related to a problem? Please describe.**
My context: package B depends on package A.
![image](https://user-images.githubusercontent.com/35262768/226671868-c7d68cc5-dc59-46d5-8484-934055d194c0.png)

If 
package A own SObject Account and have tests that insert Account records. Package A doesn't contain any TestDataSupplementer on SObject Account. 
And 
package B implement a VR and mandatory custom field on Account. Package B implement a TestDataSupplementer for that.

Then in a environment where only package A is installed the line 
```
TestDataSupplementer.supplement(accounts); 
```
will fail with error 
```
system.NullPointerException: Attempt to de-reference a null object  
Class.TestDataSupplementer.supplement: line 59, column 1     
```

**Describe the solution you'd like**
Trying to supplement a SObject that has no implemented TestDataSupplementer should not fail.

**Describe alternatives you've considered**
For now we are implementing empty TestDataSupplementer on low level package in hierarchy to avoid this problem. 

**Additional context**
All our tests in package are not 100% mocked. We mostly mock them but not always. This allow us to be able to test governor limits if needed.

Our CI is running unit test on the current package AND all unit tests of all package in a sandbox. We have a some tests that fail on the sandbox that we cannot be fixed without supplementing them. 

Our goal is to be able to always run all tests of all package inside a sandbox to have a more reliable delivery process (fail early in the development process).

When a package implement an integration test (with real insert) we would like to be able to supplement it regardless the hierarchy level.

**Comment by stohn777** [comment]
Hi @simon-nowak 
Yep.  I see the problem.  Please review PR #80.
